import {useEffect,useState} from "react";
import {AuthUser,saveTheme} from "../auth-utils";
import {DEFAULT_THEME,ThemeSettings} from "../theme-utils";
import {loadThemeStore,requestTheme,startThemeCheckout,ThemeProduct} from "../theme-store";

export function ThemeStore({user,onThemeChange}:{user:AuthUser;onThemeChange:(theme:ThemeSettings)=>void}){
 const [products,setProducts]=useState<ThemeProduct[]>([]);const [requests,setRequests]=useState<any[]>([]);const [owned,setOwned]=useState(new Set<string>());const [message,setMessage]=useState("");const [hasError,setHasError]=useState(false);const [busy,setBusy]=useState("");const [loading,setLoading]=useState(true);
 const refresh=()=>loadThemeStore(user.id).then(x=>{setProducts(x.products);setRequests(x.requests);setOwned(x.entitlements);setHasError(false)}).catch(e=>{setMessage(e.message);setHasError(true)}).finally(()=>setLoading(false));
 useEffect(()=>{refresh()},[]);
 const useTheme=async(p:ThemeProduct)=>{const next={...user.theme,...p.theme_config,mode:"custom",productId:p.id} as ThemeSettings;onThemeChange(next);await saveTheme(user.id,next);setMessage("เปิดใช้ธีมแล้ว");};
 const turnOffTheme=async()=>{onThemeChange(DEFAULT_THEME);await saveTheme(user.id,DEFAULT_THEME);setMessage("ปิดธีมแล้ว กลับมาใช้รูปแบบมาตรฐาน");};
 return <section className="theme-store"><header><p className="section-kicker">THEME STORE</p><h2>Choose your workspace</h2><p>ธีมที่ได้รับสิทธิ์จะเปลี่ยนภาพและชุดสีให้ทุกหน้าของบัญชีนี้</p></header>{loading?<p className="theme-store-state" role="status">กำลังโหลดธีม…</p>:products.length===0?<p className="theme-store-state">ยังไม่มีธีมที่เปิดให้ใช้งาน กรุณาตรวจสอบสิทธิ์ Level 2 หรือติดต่อ Admin</p>:<div className="theme-product-grid">{products.map(p=>{const req=requests.find(r=>r.product_id===p.id);const has=owned.has(p.id);const active=user.theme.productId===p.id;const collection=p.id.startsWith("hello-kitty")?"KITTY COLLECTION":p.id.startsWith("cute-shark")?"ORIGINAL CHARACTER":"SANRIO COLLECTION";return <article key={p.id} className={active?"is-active":""}><img src={p.preview_url} alt={`ตัวอย่างธีม ${p.name}`}/><div><p className="section-kicker">{collection}</p><h3>{p.name}</h3><p>{p.description}</p><strong>{active?"Theme is on":p.distribution_mode==="paid"?`฿${(p.price_satang/100).toFixed(2)}`:"Request access"}</strong></div><button aria-pressed={active} disabled={!!busy||(!has&&req?.status==="pending")} onClick={async()=>{setBusy(p.id);setMessage("");setHasError(false);try{if(has){if(active)await turnOffTheme();else await useTheme(p)}else if(p.distribution_mode==="paid")await startThemeCheckout(p.id);else{await requestTheme(user.id,p.id);await refresh();setMessage("ส่งคำขอให้ Admin แล้ว")}}catch(e){setMessage(e instanceof Error?e.message:"เกิดข้อผิดพลาด");setHasError(true)}finally{setBusy("")}}}>{has?(active?"Turn off theme":"Turn on theme →"):req?.status==="pending"?"Waiting for approval":p.distribution_mode==="paid"?"Buy with Stripe →":"Request theme →"}</button></article>})}</div>}{message&&<p className={`admin-message ${hasError?"is-error":"is-success"}`} role={hasError?"alert":"status"}>{message}</p>}</section>
}
